<?php
/**
 * Author: druphliu
 * Description
 * Email: druphliu@gmail.com
 * Created at: 2017-03-14 21:07
 */

namespace console\controllers;

use common\models\Anchor;
use common\models\LCategory;
use common\models\Platform;
use common\models\PlatformCategoryAlisa;
use phpDocumentor\Reflection\DocBlock\Tags\Author;
use yii;
use backend\models\ArticleContent;
use common\models\FriendlyLink;
use common\models\Article;
use yii\helpers\Console;
use yii\helpers\FileHelper;

set_time_limit(0);

/**
 * File attach management
 */
class SpiderController extends \yii\console\Controller
{

    private $spider;
    public $platfromId;


    public function options($actionID)
    {
        return ['platfromId'];
    }

    public function optionAliases()
    {
        return ['p_id' => 'platfromId'];
    }

    public function beforeAction($action)
    {
        $model = Platform::find()->where(['status' => 1, 'id' => $this->platfromId])->one();
        if ($model) {
            echo 'begin spader platform:' . $model->name . "\n";
            $spiderFile = __DIR__ . '/../../common/extension/live/' . $model->script;
            if (file_exists($spiderFile)) {
                echo "new obj\n";
                $className = 'common\extension\live\\' . substr($model->script, 0, strpos($model->script, '.php'));
                $this->spider = new $className();
            } else {
                die('script not exits!');
            }
        } else {
            die('plat not exits!');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 获取房间详情
     */
    public function actionGetroominfo()
    {
        echo "beign spider room\n";
        $roomList = Anchor::find()->where(['platform_id' => $this->platfromId])->andWhere('avatar is null')->all();
        foreach ($roomList as $roomModel) {
            $data = $this->spider->spiderRoom($roomModel->room_id);
            $roomModel->attributes = $data;
            $roomModel->updated_at = time();
            $roomModel->save();
            echo $roomModel->id . "\n";
        }
        echo "end spider room\n";
    }

    /**
     * 获取分类别名
     */
    public function actionAlisa()
    {
        echo "begin list\n";
        $list = $this->spider->spiderCategory();
        foreach ($list as $l) {
            $category = LCategory::find()->select('*')->where('name like "%' . $l['name'] . '%"')->one();
            if (!$category) {
                $category = new LCategory();
                $category->name = $l['name'];
                $category->alias = $l['alias'];
                $category->icon = $l['icon'];
                if (!$category->save())
                    continue;

            }
            $model = PlatformCategoryAlisa::find()->where(['l_category_id' => $category->id, 'platform_id' => $this->platfromId, 'alisa' => $l['alias']])->one();
            if ($model)
                continue;
            $model = new PlatformCategoryAlisa();
            $model->l_category_id = $category->id;
            $model->platform_id = $this->platfromId;
            $model->alisa = $l['alias'];
            $model->save();
            echo 'success' . $l['alias'] . "\n";
        }
    }

    /**
     * 获取房间列表
     */
    public function actionGetroomlist()
    {
        $categoryAlisaList = PlatformCategoryAlisa::find()->with('category')->with('platform')
            ->where(['platform_id' => $this->platfromId])
            ->andWhere('id>=211')
            ->all();
        foreach ($categoryAlisaList as $c) {
            echo $c['alisa'] . "\n";
            $list = $this->spider->spiderList($c->alisa);
            if ($list) {
                foreach ($list as $data) {
                    $model = Anchor::find()->where(['room_id' => $data['room_id'], 'platform_id' => $this->platfromId])->one();
                    if (!$model)
                        $model = new Anchor();
                    $model->room_id = $data['room_id'];
                    $model->room_url = $data['url'];
                    $model->platform_id = $this->platfromId;
                    $model->p_c_a_id = $c->id;
                    $model->platfrom_name = $c->platform->name;
                    $model->l_cid = $c->category->id;
                    $model->l_cname = $c->category->name;
                    $model->anchor_name = $data['nickname'];
                    $model->title = $data['room_name'];
                    $model->third_hn = $data['hn'];
                    $model->created_at = time();
                    $model->save();
                }
            }
        }
    }


}