<?php
/**
 * Author: druphliu
 * Description
 * Email: druphliu@gmail.com
 * Created at: 2016-06-19 00:21
 */

namespace frontend\widgets;

use yii;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\helpers\StringHelper;

class AnchorListView extends \yii\widgets\ListView
{

    public $layout = "<div class=\"game-live-list\">
                    <ul class=\"clearfix\">{items}</ul></div>
                     <div class=\"activity-type-box\">
                    <div class=\"content\">{pager}</div></div>";

    public $pagerOptions = [
        'firstPageLabel' => '首页',
        'lastPageLabel' => '尾页',
        'prevPageLabel' => '上一页',
        'nextPageLabel' => '下一页',
        'options' => [
            'class' => 'page',
        ],
    ];

    public $template = "<li>
                            <b>{platform}</b>
                            <a href=\"{url}\" target='_blank'>
                                <div class=\"play-ico\">
                                    <img src=\"{img_url}\">
                                    <i class=\"play-icon\"></i>
                                </div>
                                <div class=\"game-live-txt clearfix\">
                                    <p class=\"game-title\">{title}</p>
                                    <p class=\"game-type\">{game}</p>
                                    <p class=\"game-name\">{anchor_name}</p>
                                    <p class=\"game-hot\"><img src=\"/static/images/hot.png\">{hn}</p>
                                </div>
                            </a>
                        </li>";

    /**
     * @inheritdoc
     */
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
        $this->itemView = function ($model, $key, $index) {
            $categoryName = $model->category ? $model->category->name : yii::t('app', 'uncategoried');
            //$pubTime = yii::$app->getFormatter()->asDate($model->created_at);

            $imgUrl=$model->snapshot;
            $url = Url::to(['game/view', 'id' => $model->id]);
            $title = $model->title;
            $anchor_name = $model->anchor_name;
            $hn = $model->hn;
            $platform = $model->platfrom_name;
            return str_replace([
                '{platform}',
                '{url}',
                '{img_url}',
                '{title}',
                '{game}',
                '{anchor_name}',
                '{hn}'
            ], [
                $platform,
                $url,
                $imgUrl,
                $title,
                $categoryName,
                $anchor_name,
                $hn
            ], $this->template);
        };
    }

    /**
     * @inheritdoc
     */
    public function renderPager()
    {
        $pagination = $this->dataProvider->getPagination();
        if ($pagination === false || $this->dataProvider->getCount() <= 0) {
            return '';
        }
        /* @var $class LinkPager */
        $pager = $this->pager;
        $class = ArrayHelper::remove($pager, 'class', LinkPager::className());
        $pager['pagination'] = $pagination;
        $pager['view'] = $this->getView();
        $pager = array_merge($pager, $this->pagerOptions);
        return $class::widget($pager);
    }

}
